### ISSUE TITLE
Compiler suddenly has started failing

### ISSUE THREAD

**Issue by cbornhoft** [quaertym/ember-cli-compass-compiler#53]
This error randomly started without any changes to the compiler or options. Now when using `ember build` this is the error that pops up:

    PS C:\dev\app> ember build
    version: 1.13.8
    Building...

    Build failed.
    Command failed: C:\Windows\system32\cmd.exe /s /c "compass compile --sass-dir=app/styles
                    --css-dir='C:\dev\app\tmp\compass_compiler-tmp_cache_dir-dYFBH4rS.tmp\assets' --output-style=expanded

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

That's the entire error.

I've tried `npm uninstall --save-dev ember-cli-compass-compiler` and then reinstalling it, but this still produces the compilation error.

Anything else I can do to reset the compiler?

**Comment by cbornhoft** [comment]
Realized it wasn't the -css-dir breaking this, as that should be a tmp file.

**Comment by cbornhoft** [comment]
The solution was to manually clear the `/tmp` directory. Seems the compiler was stuck on a particular file. Once the directory was cleared and the ember server restarted, it builds as expected!
