### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by jfelchner** [quaertym/ember-cli-compass-compiler#56]
After installing `ember-cli-compass-compiler` I can't start the server:

```
ENOENT, no such file or directory '/Users/my_user/Projects/my_project/tmp/funnel-input_base_path-q1IJ0ODV.tmp/0/app/styles/'
Error: ENOENT, no such file or directory '/Users/my_user/Projects/my_project/tmp/funnel-input_base_path-q1IJ0ODV.tmp/0/app/styles/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at walkSync (/Users/my_user/Projects/my_project/node_modules/walk-sync-matcher/index.js:22:20)
    at Funnel.processFilters (/Users/my_user/Projects/my_project/node_modules/broccoli-funnel/index.js:181:15)
    at Funnel.build (/Users/my_user/Projects/my_project/node_modules/broccoli-funnel/index.js:161:10)
    at /Users/my_user/Projects/my_project/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/my_user/Projects/my_project/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/my_user/Projects/my_project/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/my_user/Projects/my_project/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/my_user/Projects/my_project/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by quaertym** [comment]
Which version are you using? Do you have the following structure?
```
app
|--styles
   |-- app.scss
```

**Comment by jfelchner** [comment]
Latest version and yeah I have `app.scss`

**Comment by quaertym** [comment]
Can you provide a repo that demonstrates the issue so that I can investigate?

**Comment by designblooz** [comment]
Remove ```broccoli-compass-compiler``` from your package.json

**Comment by jfelchner** [comment]
@designblooz obviously that would fix it. ;)

And that's what I did, but I'd really like to use compass.

**Comment by designblooz** [comment]
When you install ```ember-cli-compass-compiler``` you don't need to have ```broccoli-compass-compiler``` in your package.json. ```broccoli-compass-compiler``` is a dependency for ```ember-cli-compass-compiler```. I had the same error as you so I removed ```broccoli-compass-compiler``` from ```package.json``` as well as from ```node_modules``` and it was working fine.

**Comment by jfelchner** [comment]
@designblooz I'll give that a shot! Thanks! 😄

**Comment by quaertym** [comment]
@jfelchner Please close this if it fixes your problem.

**Comment by jfelchner** [comment]
@quaertym I will.  I'll give it a shot this weekend.

**Comment by quaertym** [comment]
@jfelchner Feel free to reopen it is not fixed.
